inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false